version: "3.9"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: react
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        ports:
            - "3001:3001"
        volumes:
            - ./server:/app